"use client";

import React, { useRef } from "react";
import type { NoteDoc } from "@/lib/schema";
import { TableView } from "./TableView";
import { DiagramView } from "./DiagramView";

interface DocumentViewProps {
  doc: NoteDoc;
  notices?: string[];
  onEdit: () => void;
  onReset: () => void;
}

export function DocumentView({
  doc,
  notices = [],
  onEdit,
  onReset,
}: DocumentViewProps) {
  const printRef = useRef<HTMLDivElement>(null);

  const handlePrint = () => {
    window.print();
  };

  return (
    <div>
      {/* Top Action Bar - Hidden in Print */}
      <div className="no-print mb-6 p-4 bg-white rounded-xl border border-slate-200 shadow-sm flex flex-col sm:flex-row justify-between items-center gap-4">
        <div className="flex items-center space-x-2">
          <span className="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-semibold bg-green-100 text-green-800">
            ✓ Document Ready
          </span>
          <span className="text-xs text-slate-500">
            {doc.sections.length} sections generated
          </span>
        </div>

        <div className="flex items-center space-x-3 w-full sm:w-auto justify-end">
          <button
            type="button"
            onClick={onReset}
            className="px-4 py-2 text-sm font-semibold rounded-lg text-slate-700 bg-slate-100 hover:bg-slate-200 focus:outline-none focus:ring-2 focus:ring-slate-500 min-h-[44px] transition-colors"
          >
            Start Over
          </button>
          <button
            type="button"
            onClick={onEdit}
            className="px-4 py-2 text-sm font-semibold rounded-lg text-blue-700 bg-blue-50 hover:bg-blue-100 border border-blue-200 focus:outline-none focus:ring-2 focus:ring-blue-600 min-h-[44px] transition-colors"
          >
            Edit Content
          </button>
          <button
            type="button"
            onClick={handlePrint}
            className="px-5 py-2 text-sm font-bold rounded-lg text-white bg-blue-600 hover:bg-blue-700 shadow focus:outline-none focus:ring-2 focus:ring-blue-600 min-h-[44px] flex items-center space-x-1.5 transition-colors"
          >
            <span>🖨️</span>
            <span>Print / Save as PDF</span>
          </button>
        </div>
      </div>

      {/* Partial Failure Notices */}
      {notices && notices.length > 0 && (
        <div className="no-print mb-6 p-4 rounded-xl bg-amber-50 border border-amber-200 text-xs text-amber-900">
          <strong className="block font-bold mb-1">Partial formatting notice:</strong>
          <ul className="list-disc pl-4 space-y-1">
            {notices.map((n, i) => (
              <li key={i}>{n}</li>
            ))}
          </ul>
        </div>
      )}

      {/* Flagged readings alert */}
      {doc.uncertain && doc.uncertain.length > 0 && (
        <aside
          aria-label="Flagged readings warning"
          className="no-print mb-6 p-4 rounded-xl bg-amber-50 border border-amber-200 text-amber-950"
        >
          <div className="flex items-center space-x-2 mb-1">
            <span aria-hidden="true">⚠️</span>
            <h2 className="text-sm font-bold">Readings to double-check ({doc.uncertain.length})</h2>
          </div>
          <p className="text-xs text-amber-800 mb-2">
            The AI flagged the following readings from your notes as slightly ambiguous or uncertain. You can click &quot;Edit Content&quot; to adjust them:
          </p>
          <ul className="space-y-1 text-xs">
            {doc.uncertain.map((item, idx) => (
              <li key={idx} className="flex items-start gap-2">
                <span className="font-semibold text-amber-900">&bull; &ldquo;{item.text}&rdquo;:</span>
                <span className="text-slate-700">{item.reason}</span>
              </li>
            ))}
          </ul>
        </aside>
      )}

      {/* Printable Semantic Study Document */}
      <article
        ref={printRef}
        className="print-document bg-white rounded-2xl shadow-sm border border-slate-200 p-8 md:p-12 text-slate-900"
      >
        <header className="border-b-2 border-slate-900 pb-6 mb-8">
          <h1 className="text-3xl sm:text-4xl font-black tracking-tight text-slate-950 mb-3">
            {doc.title}
          </h1>
          {doc.summary && (
            <p className="text-base sm:text-lg text-slate-700 leading-relaxed font-normal">
              {doc.summary}
            </p>
          )}
          <div className="mt-4 pt-3 border-t border-slate-200 text-xs text-slate-500 flex justify-between items-center">
            <span>Generated by NoteForge Study Guide Synthesizer</span>
            <span>{new Date().toLocaleDateString(undefined, { year: "numeric", month: "long", day: "numeric" })}</span>
          </div>
        </header>

        <div className="space-y-10">
          {doc.sections.map((section, idx) => (
            <section key={idx} className="space-y-4">
              <h2 className="text-xl sm:text-2xl font-bold tracking-tight text-slate-900 border-b border-slate-200 pb-2">
                {section.heading}
              </h2>

              {section.paragraphs && section.paragraphs.length > 0 && (
                <div className="space-y-3">
                  {section.paragraphs.map((p, pIdx) => (
                    <p key={pIdx} className="text-sm sm:text-base text-slate-800 leading-relaxed">
                      {p}
                    </p>
                  ))}
                </div>
              )}

              {section.bullets && section.bullets.length > 0 && (
                <ul className="list-disc pl-6 space-y-2 text-sm sm:text-base text-slate-800">
                  {section.bullets.map((bullet, bIdx) => (
                    <li key={bIdx} className="leading-relaxed">
                      {bullet}
                    </li>
                  ))}
                </ul>
              )}

              {section.table && <TableView table={section.table} />}

              {section.diagram && <DiagramView diagram={section.diagram} />}
            </section>
          ))}
        </div>
      </article>
    </div>
  );
}
